name: udacity-gen-ai
channels:
  - defaults
  - pytorch
  - nvidia
  - anaconda 
dependencies:
  - python
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - transformers
  - openai=0.27
  - numpy
  - pandas
  - ipykernel
  - matplotlib
  - pip
  - beautifulsoup4
  - pip:
    - diffusers
    - scikit-learn
    - peft
    - tiktoken
    - face-recognition
    - ema_pytorch
    - opencv-python